nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3100']  # autorise le domaine Next.js
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['http://localhost:3100']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            max_age: 3600
